CREATE TABLE IF NOT EXISTS app_meta (version INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS customer (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(150) NOT NULL, phone VARCHAR(40) NOT NULL, email VARCHAR(150) NOT NULL
);
CREATE TABLE IF NOT EXISTS vehicle (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 plate VARCHAR(7) NOT NULL UNIQUE, brand VARCHAR(80) NOT NULL, model VARCHAR(100) NOT NULL,
 mileage BIGINT NOT NULL CHECK (mileage >= 0), manufacture_year INTEGER NOT NULL CHECK (manufacture_year >= 1886),
 customer_id BIGINT NOT NULL REFERENCES customer(id), UNIQUE(id, customer_id)
);
CREATE TABLE IF NOT EXISTS service_order (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id BIGINT NOT NULL REFERENCES customer(id), vehicle_id BIGINT NOT NULL,
 complaint VARCHAR(2000) NOT NULL, entry_date DATE NOT NULL, mileage BIGINT NOT NULL CHECK(mileage >= 0),
 responsible VARCHAR(150) NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('OPEN','APPROVED','REJECTED','CLOSED','CANCELLED')),
 diagnosis VARCHAR(4000) NOT NULL DEFAULT '',
 decision_at TIMESTAMP, decision_by VARCHAR(150), budget_total DECIMAL(15,2),
 payment_method VARCHAR(40), pickup_date DATE,
 FOREIGN KEY(vehicle_id, customer_id) REFERENCES vehicle(id, customer_id)
);
-- A chave primaria impede duas OS ativas para o mesmo veiculo, inclusive em transacoes concorrentes.
CREATE TABLE IF NOT EXISTS active_order (
 vehicle_id BIGINT PRIMARY KEY REFERENCES vehicle(id),
 order_id BIGINT NOT NULL UNIQUE REFERENCES service_order(id)
);
CREATE TABLE IF NOT EXISTS part (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(150) NOT NULL UNIQUE, unit_price DECIMAL(12,2) NOT NULL CHECK(unit_price > 0),
 stock INTEGER NOT NULL CHECK(stock >= 0)
);
CREATE TABLE IF NOT EXISTS order_item (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL REFERENCES service_order(id),
 kind VARCHAR(10) NOT NULL CHECK(kind IN ('SERVICE','PART')),
 description VARCHAR(200) NOT NULL, quantity INTEGER NOT NULL CHECK(quantity > 0),
 unit_price DECIMAL(12,2) NOT NULL CHECK(unit_price > 0),
 part_id BIGINT REFERENCES part(id), completed BOOLEAN NOT NULL DEFAULT FALSE,
 CHECK((kind = 'SERVICE' AND part_id IS NULL) OR (kind = 'PART' AND part_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_order_date ON service_order(entry_date);
CREATE INDEX IF NOT EXISTS idx_item_order ON order_item(order_id);

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK(role IN ('GERENTE', 'ATENDENTE', 'MECANICO'))
);

